service: lamda-first

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'ca-central-1'}
  environment: 
    STAGE: ${opt:stage, 'dev'}

functions:
  lamda-first:
    handler: functions/lamda-first.handler
  

